name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs everyday
    - cron: "0 0 * * *"

jobs:
  update-readme:
    permissions:
      contents: write
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
